# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  win10:
    runs-on: windows:
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            make
            mingw64/mingw-w64-x86_64-gcc
            mingw64/mingw-w64-x86_64-cmake
            mingw64/mingw-w64-x86_64-zlib
            mingw64/mingw-w64-x86_64-libuv
            mingw64/mingw-w64-x86_64-mbedtls
            mingw64/mingw-w64-x86_64-json-c
          update: true
      - name: Build ttyd
        shell: msys2 {0}
        run: ./scripts/mingw-build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ttyd.win10
          path: build/ttyd.exe
