# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  win10:
    runs-on: windows-latest
    steps:
      - name: Avoid line ending issues on Windows
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
        with: 
          ref: 1.5.2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            make
            mingw64/mingw-w64-x86_64-gcc
            mingw64/mingw-w64-x86_64-cmake
            mingw64/mingw-w64-x86_64-zlib
            mingw64/mingw-w64-x86_64-libuv
            mingw64/mingw-w64-x86_64-mbedtls
            mingw64/mingw-w64-x86_64-json-c
            mingw64/mingw-w64-x86_64-libwebsockets
            git 
            binutils
          update: true
      - name: Build ttyd
        shell: msys2 {0}
        run: |
            cd ./msys2/ttyd
            pacman -S --noconfirm  binutils 
            sed -i "s/'gcc'/mingw-w64-x86_64-gcc/g" PKGBUILD
            sed -i "s/'cmake'/mingw-w64-x86_64-cmake/g" PKGBUILD
            sed -i "s/'json-c'/mingw-w64-x86_64-json-c/g" PKGBUILD
            sed -i "s/'libwebsockets'/mingw-w64-x86_64-libwebsockets/g" PKGBUILD
            makepkg --noconfirm --noprogressbar --skipchecksums
      - uses: actions/upload-artifact@v2
        with:
          name: ttyd.win10
          path: build/ttyd.exe
